name = "BeForData"
uuid = "49581401-e3b0-43cb-bb9c-49750952130d"
version = "0.3.9-dev"
authors = ["Oliver Lindemann"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
XDF = "31bc19ec-0089-417f-990e-a2b5e7515868"

[extensions]
ArrowExt = ["Arrow"]
FilteringExt = ["DSP"]
XdfExt = ["XDF"]

[compat]
Aqua = "0.8"
Arrow = "1, 2"
DSP = "0.8"
DataFrames = "1"
EzXML = "1"
JSON = "1"
Statistics = "1"
Test = "1"
XDF = "0.2"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
